CREATE TABLE tasks (
    id INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) DEFAULT NULL,
    description MEDIUMTEXT,
    author VARCHAR(100) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    PRIMARY KEY(id)
)